name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main branch
        run: git merge upstream/main --no-edit

      - name: Push changes to origin
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT }}
