name: Sync Upstream Repository

on:

  schedule:

    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  sync:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v2

      - name: Set up Git user

        run: |

          git config --global user.name "woshishiq1"

          git config --global user.email "1987669587@qq.com"

      - name: Sync upstream repository

        run: |

          git remote add upstream "https://github.com/woshishiqioc/ceshi.git"

          git fetch upstream

          git checkout main


          git merge upstream/master

          git push
